routes/web.php
<?php

use App\Http\Controllers\ChecklistController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::permanentRedirect('/', 'register');

Route::middleware(['auth'])->group(function () {
    Route::resource('checklists', ChecklistController::class);
    Route::resource('tasks', TaskController::class);
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Checklist.php
<?php

namespace App\Models;

use App\Traits\Filter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Checklist extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'id',
        'name',
        'user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use App\Traits\Filter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'id',
        'title',
        'checklist_id',
        'status'
    ];

    public const STATUS = ['To Do', 'Done'];

    public function checklist()
    {
        return $this->belongsTo(Checklist::class);
    }

    public function scopeFilterStatus($query, $filter)
    {
        if (in_array($filter, self::STATUS)) {
            return $query->where('status', $filter);
        }
        return $query;
    }

    public function scopeFilterSorting($query, $filter)
    {
        if ($filter) {
            return $query->orderBy('created_at', 'ASC');
        }
        return $query;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ChecklistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Checklist;
use App\Models\User;
use Illuminate\Http\Request;

class ChecklistController extends Controller
{
    public function index()
    {
        $checklists = Checklist::all();

        return view('checklists.index', compact('checklists'));
    }

    public function create()
    {
        $users = User::all('id', 'name');

        return view('checklists.create', compact('users'));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate(
            [
                'name' => 'required',
                'user_id' => 'required'
            ]
        );

        Checklist::create($validatedData);

        return redirect()->route('checklists.index');
    }


    public function show(Checklist $checklist)
    {
        $checklist->load('tasks', 'user');

        return view('checklists.show', compact('checklist'));
    }

    public function edit(Checklist $checklist)
    {
        $users = User::all('id', 'name');

        return view('checklists.edit', compact('checklist', 'users'));
    }

    public function update(Request $request, Checklist $checklist)
    {
        $validatedData = $request->validate(
            [
                'name' => 'required'
            ]
        );

        $checklist->update($validatedData);

        return redirect()->route('checklists.index');
    }

    public function destroy(Checklist $checklist)
    {
        $checklist->delete();

        return redirect()->route('checklists.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaskRequest;
use App\Models\Checklist;
use App\Models\Task;
use App\Models\User;

class TaskController extends Controller
{
    public function index()
    {
        $tasks = Task::with(['checklist'])
            ->FilterStatus(request('status'))
            ->FilterSorting(request('sort'))
            ->get();

        return view('tasks.index', compact('tasks'));
    }

    public function create()
    {
        $checklists = Checklist::all('id', 'name');

        return view('tasks.create', compact('checklists'));
    }

    public function store(TaskRequest $request)
    {
        Task::create($request->validated());

        return redirect()->route('tasks.index');
    }

    public function show(Task $task)
    {
        return view('tasks.show', compact('task'));
    }

    public function edit(Task $task)
    {
        $checklists = Checklist::all('id', 'name');

        return view('tasks.edit', compact('task', 'checklists'));
    }

    public function update(TaskRequest $request, Task $task)
    {
        $task->update($request->validated());

        return redirect()->route('tasks.index');
    }

    public function destroy(Task $task)
    {
        $task->delete();

        return redirect()->route('tasks.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/checklists/create.blade.php
@extends('dashboard.layout')

@section('content')
    <form action="{{ route('checklists.store') }}" method="POST">
        @csrf

        <div class="card">
            <div class="card-header">
                Create Checklist
            </div>
            <div class="card-body">
                <x-input-field name="name" label="Name"/>

                <div class="form-group mt-2">
                    <label for="user_id">Assigned user</label>
                    <select
                            class="form-control mt-2{{ $errors->has('user_id') ? 'is-invalid' : '' }}"
                            name="user_id"
                            id="user_id"
                            required
                    >
                        @foreach($users as $user)
                            <option value="{{ $user->id }}" {{ (old('user_id') ? old('user_id') : $project->user->id ?? '') == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
                        @endforeach
                    </select>

                    @if($errors->has('user_id'))
                        <div class="invalid-feedback">
                            {{ $errors->first('user') }}
                        </div>
                    @endif
                    <span class="help-block"> </span>
                </div>

                <button class="btn btn-primary mt-4" type="submit">
                    Save
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/checklists/edit.blade.php
@extends('dashboard.layout')

@section('content')
    <div class="row">
        <div class="col-md-8">
            <form action="{{ route('checklists.update', $project) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="card">
                    <div class="card-header">
                        Edit project
                    </div>

                    <div class="card-body">
                        <x-input-field name="title" label="Title" oldValue="{{ $project->title }}"/>

                        <div class="form-group">
                            <label class="required" for="description">Description</label>
                            <textarea class="form-control mt-2 {{ $errors->has('contact_email') ? 'is-invalid' : '' }}"
                                      rows="10" name="description"
                                      id="description">{{ old('description', $project->description) }}</textarea>
                            @if($errors->has('contact_email'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('contact_email') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <div class="form-group mt-2">
                            <label for="deadline">Deadline</label>
                            <input class="form-control mt-2 {{ $errors->has('deadline') ? 'is-invalid' : '' }}" type="date"
                                   name="deadline" id="deadline" value="{{ old('deadline', $project->deadline) }}">
                            @if($errors->has('deadline'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('deadline') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <div class="form-group mt-2">
                            <label for="user_id">Assigned user</label>
                            <select
                                    class="form-control mt-2{{ $errors->has('user_id') ? 'is-invalid' : '' }}"
                                    name="user_id"
                                    id="user_id"
                                    required
                            >
                                @foreach($users as $user)
                                    <option value="{{ $user->id }}" {{ (old('user_id') ? old('user_id') : $project->user->id ?? '') == $user->id ? 'selected' : '' }}>{{ $user->first_name. ' '. $user->last_name }}</option>
                                @endforeach
                            </select>

                            @if($errors->has('user_id'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('user') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <div class="form-group mt-2">
                            <label for="client_id">Assigned client</label>
                            <select class="form-control mt-2 {{ $errors->has('client_id') ? 'is-invalid' : '' }}"
                                    name="client_id" id="client_id" required>
                                @foreach($clients as $id => $entry)
                                    <option
                                            value="{{ $id }}" {{ (old('client_id') ? old('client_id') : $project->client->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('client_id'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('client_id') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <div class="form-group mt-2">
                            <label for="status">Status</label>
                            <select class="form-control mt-2 {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status"
                                    id="status" required>
                                @foreach(App\Models\Project::STATUS as $status)
                                    <option
                                            value="{{ $status }}" {{ (old('status') ? old('status') : $project->status ?? '') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('status'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('status') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <button class="btn btn-primary mt-4" type="submit">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/checklists/index.blade.php
@extends('dashboard.layout')

@section('content')
    <div
            style="margin-bottom: 10px"
            class="row"
    >
        <div class="col-lg-12">
            <a
                    href="{{ route('checklists.create') }}"
                    class="btn btn-success text-white"
            >Create Checklist
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Checklists list
        </div>

        <div class="card-body">
            <table class="table table-responsive-sm table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Assigned to</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($checklists as $checklist)
                    <tr>

                        <td>
                            <a
                                    style="text-decoration: none"
                                    href="{{ route('checklists.show', $checklist) }}"
                            >{{ $checklist->name }}</a>
                        </td>
                        <td>{{ $checklist->user->name }}</td>
                        <td>
                            <a
                                    class="btn btn-sm btn-info text-white"
                                    href="{{ route('checklists.edit', $checklist) }}"
                            >
                                Edit
                            </a>
                        </td>
                        <td>
                            <form
                                    action="{{ route('checklists.destroy', $checklist) }}"
                                    method="POST"
                                    onsubmit="return confirm('Are your sure?');"
                                    style="display: inline-block;"
                            >
                                @method('DELETE')
                                <input
                                        type="hidden"
                                        name="_method"
                                        value="DELETE"
                                >
                                <input
                                        type="hidden"
                                        name="_token"
                                        value="{{ csrf_token() }}"
                                >
                                <input
                                        type="submit"
                                        class="btn btn-sm btn-danger text-white"
                                        value="Delete"
                                >
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/checklists/show.blade.php
@extends('dashboard.layout')

@section('content')
    <div class="row">

        <div class="col-md-6">
            <div class="card">
                <div class="card-header" style="background-color: #FEFCFB;">Assigned user</div>

                <div class="card-body">
                    <p class="mb-0">{{ $checklist->user->name }}</p>
                    <p class="mb-0">{{ $checklist->user->email }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-8 mt-4">
            <div class="card border-top-primary">
                <div class="card-header" style="background-color: #FEFCFB;">
                    {{ $checklist->name }}
                </div>
            </div>
        </div>

        <div class="col-md-4 mt-4 border-top-danger">
            <div class="card border-top-primary">
                <div class="card-header" style="background-color: #FEFCFB;">Information</div>

                <div class="card-body">
                    <p class="mb-0">Created at {{ $checklist->created_at->format('M d, Y') }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-12 mt-4">
            <div class="card border-top-primary">
                <div class="card-header">Tasks</div>
                <div class="card-body">
                    @if($checklist->tasks->count())
                        <table class="table table-sm table-responsive-sm">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Assigned to</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($checklist->tasks as $task)
                                <tr>
                                    <td>
                                        <a style="text-decoration: none" href="{{ route('tasks.show', $task) }}">{{ $task->title }}</a>
                                    </td>
                                    <td>{{ $task->status }}</td>
                                    <td>
                                        <a
                                                class="btn btn-sm btn-info"
                                                href="{{ route('tasks.edit', $task) }}"
                                        >
                                            Edit
                                        </a>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div
                                class="alert alert-info"
                                role="alert"
                        >
                            No tasks added to this project.
                            <a href="{{ route('tasks.create') }}">Create task now.</a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard.blade.php
@extends('dashboard.layout')

@section('content')
    <div class="card">
        <div class="card-header">{{ __('Dashboard') }}</div>

        <div class="card-body">
            {{ __('You are logged in!') }}
        </div>
    </div>
@endsection()

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/tasks/create.blade.php
@extends('dashboard.layout')

@section('content')
    <form action="{{ route('tasks.store') }}" method="POST">
        @csrf

        <div class="card">
            <div class="card-header">
                Create Task
            </div>
            <div class="card-body">
                <x-input-field name="title" label="Title"/>

                <div class="form-group mt-2">
                    <label for="checklist_id">Assigned Checklist</label>
                    <select class="form-control mt-2 {{ $errors->has('checklist_id') ? 'is-invalid' : '' }}"
                            name="checklist_id" id="checklist_id" required>
                        @foreach($checklists as $checklist)
                            <option
                                    value="{{ $checklist->id }}" {{ (old('checklist_id') ? old('checklist_id') : $checklist->id ?? '') == $checklist->id ? 'selected' : '' }}>{{ $checklist->name }}
                            </option>
                        @endforeach
                    </select>
                    @if($errors->has('checklist_id'))
                        <div class="invalid-feedback">
                            {{ $errors->first('checklist_id') }}
                        </div>
                    @endif
                    <span class="help-block"> </span>
                </div>

                <div class="form-group mt-2">
                    <label for="status">Status</label>
                    <select class="form-control mt-2 {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status"
                            id="status" required>
                        @foreach(App\Models\Task::STATUS as $status)
                            <option
                                    value="{{ $status }}" {{ old('status') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                        @endforeach
                    </select>
                    @if($errors->has('status'))
                        <div class="invalid-feedback">
                            {{ $errors->first('status') }}
                        </div>
                    @endif
                    <span class="help-block"> </span>
                </div>

                <button class="btn btn-primary mt-4" type="submit">
                    Save
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/tasks/edit.blade.php
@extends('dashboard.layout')

@section('content')
    <div class="row">
        <div class="col-md-8">
            <form action="{{ route('tasks.update', $task) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="card">
                    <div class="card-header">
                        Edit task
                    </div>

                    <div class="card-body">
                        <x-input-field name="title" label="Title" oldValue="{{ $task->title }}"/>

                        <div class="form-group mt-2">
                            <label for="checklist_id">Assigned Checklist</label>
                            <select class="form-control mt-2 {{ $errors->has('checklist_id') ? 'is-invalid' : '' }}"
                                    name="checklist_id" id="checklist_id" required>
                                @foreach($checklists as $checklist)
                                    <option
                                            value="{{ $checklist->id }}" {{ (old('checklist_id') ? old('checklist_id') : $checklist->id ?? '') == $checklist->id ? 'selected' : '' }}>{{ $checklist->name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('checklist_id'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('checklist_id') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <div class="form-group mt-2">
                            <label for="status">Status</label>
                            <select class="form-control mt-2 {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status"
                                    id="status" required>
                                @foreach(App\Models\Task::STATUS as $status)
                                    <option
                                            value="{{ $status }}" {{ (old('status') ? old('status') : $task->status ?? '') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('status'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('status') }}
                                </div>
                            @endif
                            <span class="help-block"> </span>
                        </div>

                        <button class="btn btn-primary mt-4" type="submit">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('dashboard.layout')

@section('content')
    <div
            style="margin-bottom: 10px"
            class="row"
    >
        <div class="col-lg-12">
            <a
                    href="{{ route('tasks.create') }}"
                    class="btn btn-success text-white"
            >Create Task
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Tasks list
        </div>

        <div class="card-body">
            <div class="d-flex justify-content-end">
                <form action="{{ route('tasks.index') }}" method="GET">
                        <div class="form-group row">
                            <label for="sorting" class="col-form-label">To Sort press here</label>
                            <div class="col-sm-8">
                                <button
                                        name="sort"
                                        id="sort"
                                        class="form-control btn btn-ghost-danger"
                                        value="true"
                                        onclick="this.form.submit()"
                                >
                                    Sort
                                </button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="status" class="col-form-label">Status:</label>
                            <div class="col-sm-8">
                                <select
                                        name="status"
                                        id="status"
                                        class="form-control"
                                        onchange="this.form.submit()"
                                >
                                    <option value="All" {{ request('filter') == 'all' ? 'selected' : '' }}>All</option>
                                    @foreach(\App\Models\Task::STATUS as $status)
                                        <option value="{{ $status }}" {{ request('status') == $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                </form>
            </div>
            <hr class="solid">
            <table class="table table-responsive-sm table-striped">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Status</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($tasks as $task)
                    <tr>
                        <td>
                            <a style="text-decoration: none" href="{{ route('tasks.show', $task) }}">{{ $task->title }}</a></td>
                        <td>{{ $task->status }}</td>
                        <td>
                            <a class="btn btn-sm btn-info text-white" href="{{ route('tasks.edit', $task) }}">
                                Edit
                            </a>
                        </td>
                            <td>
                                <form
                                        action="{{ route('tasks.destroy', $task) }}"
                                        method="POST"
                                        onsubmit="return confirm('Are your sure?');"
                                        style="display: inline-block;"
                                >
                                    @method('DELETE')
                                    <input
                                            type="hidden"
                                            name="_method"
                                            value="DELETE"
                                    >
                                    <input
                                            type="hidden"
                                            name="_token"
                                            value="{{ csrf_token() }}"
                                    >
                                    <input
                                            type="submit"
                                            class="btn btn-sm btn-danger text-white"
                                            value="Delete"
                                    >
                                </form>
                            </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection